name: Node.js Demos

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'demo/nodejs/**'
      - '!demo/nodejs/README.md'
      - '.github/workflows/nodejs-demos.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/nodejs/**'
      - '!demo/nodejs/README.md'
      - '.github/workflows/nodejs-demos.yml'

defaults:
  run:
    working-directory: demo/nodejs

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Install dependencies
      run: yarn install

    - name: Run get audio devices
      run: node demo.js --show_audio_devices

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone, pv-windows]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Install dependencies
      run: yarn install

    - name: Run get audio devices
      run: node demo.js --show_audio_devices
