name: Python

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'binding/python/**'
      - '!binding/python/README.md'
      - 'lib/beaglebone/**'
      - 'lib/linux/**'
      - 'lib/jetson/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/python/**'
      - '!binding/python/README.md'
      - 'lib/beaglebone/**'
      - 'lib/linux/**'
      - 'lib/jetson/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - '.github/workflows/python.yml'

defaults:
  run:
    working-directory: binding/python

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test
      run: python3 test_pv_recorder.py

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone, pv-windows]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Test
      run: python3 test_pv_recorder.py
      if: ${{ matrix.machine != 'pv-windows' }}

    - name: Test
      run: python test_pv_recorder.py
      if: ${{ matrix.machine == 'pv-windows' }}
